version: '3.4'

services:
  rabbitmq:
    image: "rabbitmq:3.9-management"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  modularmonolith.api:
    image: ${DOCKER_REGISTRY-}modularmonolithapi
    build:
      context: .
      dockerfile: ModularMonolith.API/Dockerfile
    depends_on:
      - "rabbitmq"
